 To create table from JSON
CREATE OR REPLACE TABLE "RETAIL"."BRONZE"."AB" ( ADDRESSLINE1 VARCHAR , ADDRESSLINE2 VARCHAR , CITY VARCHAR , CONTACTFIRSTNAME VARCHAR , CONTACTLASTNAME VARCHAR , COUNTRY VARCHAR , CUSTOMERNAME VARCHAR , DEALSIZE VARCHAR , MONTH_ID VARCHAR , MSRP VARCHAR , ORDERDATE VARCHAR , ORDERLINENUMBER VARCHAR , ORDERNUMBER VARCHAR , PHONE VARCHAR , POSTALCODE VARCHAR , PRICEEACH VARCHAR , PRODUCTCODE VARCHAR , PRODUCTLINE VARCHAR , QTR_ID VARCHAR , QUANTITYORDERED VARCHAR , SALES VARCHAR , STATE VARCHAR , STATUS VARCHAR , TERRITORY VARCHAR , YEAR_ID VARCHAR , UPDATEDAT TIMESTAMP_NZ); 

CREATE TEMP FILE FORMAT "RETAIL"."BRONZE"."TEMP"
	TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "RETAIL"."BRONZE"."AB" 
FROM (SELECT $1:ADDRESSLINE1::VARCHAR, $1:ADDRESSLINE2::VARCHAR, $1:CITY::VARCHAR, $1:CONTACTFIRSTNAME::VARCHAR, $1:CONTACTLASTNAME::VARCHAR, $1:COUNTRY::VARCHAR, $1:CUSTOMERNAME::VARCHAR, $1:DEALSIZE::VARCHAR, $1:MONTH_ID::VARCHAR, $1:MSRP::VARCHAR, $1:ORDERDATE::VARCHAR, $1:ORDERLINENUMBER::VARCHAR, $1:ORDERNUMBER::VARCHAR, $1:PHONE::VARCHAR, $1:POSTALCODE::VARCHAR, $1:PRICEEACH::VARCHAR, $1:PRODUCTCODE::VARCHAR, $1:PRODUCTLINE::VARCHAR, $1:QTR_ID::VARCHAR, $1:QUANTITYORDERED::VARCHAR, $1:SALES::VARCHAR, $1:STATE::VARCHAR, $1:STATUS::VARCHAR, $1:TERRITORY::VARCHAR, $1:YEAR_ID::VARCHAR
	FROM '@"RETAIL"."BRONZE"."BRONZESTG"') 
FILES = ('JSONSNW1100.json') 
FILE_FORMAT = RETAIL.BRONZE.JSON_FORMAT
ON_ERROR=ABORT_STATEMENT 
